### ISSUE TITLE
Template processing order issue with Ember CLI v3.2

### ISSUE THREAD

**Issue by josemarluedke** [ember-learn/ember-cli-addon-docs#200]
Getting this error when upgrading to Ember CLI 3.2: `Templates contents haven't been extracted yet`.

It might be that ec-addon-docs was relying on the order that Ember CLI was processing the templates.

Here is the full log: https://gist.github.com/josemarluedke/e86327831aeae56fd62b17309a7ed56f

**Comment by lifeart** [comment]
```
=================================================================================

ENV Summary:

  TIME: Sat Jul 07 2018 23:09:11 GMT+0300 (GMT+03:00)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\lifeart\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - s
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\lifeart\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Program Files (x86)\Intel\iCLS Client\;C
  - \Program Files\Intel\iCLS Client\;C
  - \ProgramData\Oracle\Java\javapath;C
  - \Python27\Lib\site-packages\PyQt4;C
  - \Python27\;C
  - \Python27\Scripts;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C
  - \Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C
  - \Program Files\Microsoft\Web Platform Installer\;C
  - \Program Files (x86)\Bitvise SSH Client;C
  - \Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C
  - \Program Files (x86)\Lenovo\Password Manager\;C
  - \Program Files (x86)\Lenovo\Access Connections\;C
  - \Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C
  - \Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\bin;C
  - \Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\cmd;C
  - \Program Files\TortoiseHg\;C
  - \Program Files (x86)\WinMerge;C
  - \Program Files (x86)\QuickTime\QTSystem\;C
  - \Program Files\Intel\WiFi\bin\;C
  - \Program Files\Common Files\Intel\WirelessCommon\;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\WIDCOMM\Bluetooth Software\;C
  - \Program Files\WIDCOMM\Bluetooth Software\syswow64;C
  - \Program Files\Git\cmd;C
  - \Program Files (x86)\Skype\Phone\;C
  - \Program Files\erl9.2\bin;C
  - \Program Files (x86)\Elixir\bin;C
  - \Users\lifeart\.mix\escripts;C
  - \Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C
  - \Program Files\TortoiseGit\bin;C
  - \Users\lifeart\AppData\Roaming\nvm;C
  - \Program Files\nodejs;C
  - \Program Files\nodejs\;C
  - \Users\lifeart\scoop\shims;C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Program Files (x;C
  - \Users\lifeart\AppData\Local\GitHub\PortableGit_PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin;C
  - \Users\lifeart\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd;C
  - \MinGW\bin;C
  - \Users\lifeart\AppData\Local\atom\bin;C
  - \Program Files (x86)\Toon Boom Animation\Toon Boom Harmony 10.0\win64\bin;C
  - \Program Files (x86)\Toon Boom Animation\Toon Boom Harmony 10.0\win32\bin;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Program Files\Docker Toolbox;C
  - \Users\lifeart\AppData\Local\GitHubDesktop\bin;C
  - \Users\lifeart\AppData\Roaming\nvm;C
  - \Users\lifeart\AppData\Roaming\npm;C
  - \Users\lifeart\AppData\Local\Keybase\
  PLATFORM: win32 x64
  FREEMEM: 5704822784
  TOTALMEM: 16862322688
  UPTIME: 34704
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz - 2893
  - Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz - 2893
  - Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz - 2893
  - Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz - 2893
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.0
  - http_parser: 2.8.0
  - icu: 61.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.4.1
  - openssl: 1.1.0h
  - tz: 2018c
  - unicode: 10.0
  - uv: 1.20.3
  - v8: 6.7.288.45-node.7
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Templates contents haven't been extracted yet
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Templates contents haven't been extracted yet
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Templates contents haven't been extracted yet
    at HBSContentExtractor.getTemplateContentsTree (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli-addon-docs\lib\preprocessors\hbs-content-extractor.js:14:13)
    at Class.treeForPublic (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli-addon-docs\index.js:196:54)
    at Class.superWrapper [as treeForPublic] (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class._treeFor (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli\lib\models\addon.js:583:33)
    at Class.treeFor (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli\lib\models\addon.js:543:21)
    at project.addons.reduce (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli\lib\broccoli\ember-app.js:660:26)
    at Array.reduce (<anonymous>)
    at EmberAddon._addonTreesFor (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli\lib\broccoli\ember-app.js:658:32)
    at EmberAddon.addonTreesFor (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli\lib\broccoli\ember-app.js:682:17)
    at EmberAddon.toArray (C:\Users\lifeart\Documents\Repositories\ember-cerebraljs\node_modules\ember-cli\lib\broccoli\ember-app.js:1896:33)

=================================================================================

```

**Comment by dfreeman** [comment]
Hi @nightire—sorry about that! We fixed it on `master` but didn't actually release a new version to the npm registry until today. If you install `ember-cli-addon-docs@0.5.2`, it should work with ember-cli 3.2 and 3.3.

**Comment by nightire** [comment]
@dfreeman Sorry I forgot to say I did tested it against the master branch, and I saw a new error:

```
Build Error (SearchIndexCompiler)

projectVersionDoc.included is not iterable


Stack Trace and Error Report: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T/error.dump.0a80ea2c54cdb29631e6d723f4dd09ab.log
```

Here is the log:

```
ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: projectVersionDoc.included is not iterable
    at SearchIndexCompiler.buildApiItemDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:87:40)
    at buildApiItemDocuments.next (<anonymous>)
    at SearchIndexCompiler.buildDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:53:21)
    at buildDocuments.next (<anonymous>)
    at lunr.Builder.<anonymous> (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:32:16)
    at lunr (/Users/nightire/Code/choice-form/ui-lottie/node_modules/lunr/lunr.js:53:10)
    at SearchIndexCompiler.build (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:22:17)
    at /Users/nightire/Code/choice-form/ui-lottie/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:538:13)
  - codeFrame: projectVersionDoc.included is not iterable
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SearchIndexCompiler` plugin. 💥
projectVersionDoc.included is not iterable
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SearchIndexCompiler` plugin. 💥
projectVersionDoc.included is not iterable
  - name: Error
  - nodeAnnotation: SearchIndexCompiler
  - nodeName: SearchIndexCompiler
  - originalErrorMessage: projectVersionDoc.included is not iterable
  - stack: TypeError: projectVersionDoc.included is not iterable
    at SearchIndexCompiler.buildApiItemDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:87:40)
    at buildApiItemDocuments.next (<anonymous>)
    at SearchIndexCompiler.buildDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:53:21)
    at buildDocuments.next (<anonymous>)
    at lunr.Builder.<anonymous> (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:32:16)
    at lunr (/Users/nightire/Code/choice-form/ui-lottie/node_modules/lunr/lunr.js:53:10)
    at SearchIndexCompiler.build (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:22:17)
    at /Users/nightire/Code/choice-form/ui-lottie/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:538:13)

=================================================================================
```

try with my repo, I've already upgrade to `ember-cli-addon-docs@0.5.2`.

**Comment by dfreeman** [comment]
Uh oh, that sounds like a separate bug. Could you please file a new issue?
