### ISSUE TITLE
Ember Data warnings with newer Ember version

### ISSUE THREAD

**Issue by josemarluedke** [ember-learn/ember-cli-addon-docs#221]
I'm using Ember v3.3 in my addon which adds a few deprecations to Ember Data.

Here is an example:

```
        Log: |
            { type: 'warn',
              text:
               '\'DEPRECATION: Use of @ember/MapWithDefault is deprecated. Please use native `Map` instead [deprecation id: ember-map-deprecation]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17922:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:18024:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17946:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:18024:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:18033:17)\\n        at deprecate (http://localhost:7357/assets/vendor.js:18005:34)\\n        at new MapWithDefault (http://localhost:7357/assets/vendor.js:19517:51)\\n        at Function.create (http://localhost:7357/assets/vendor.js:19542:18)\\n        at Class.init (http://localhost:7357/assets/vendor.js:147683:47)\'\n' }
            { type: 'warn',
              text:
               '\'DEPRECATION: Use of @ember/Map is deprecated. Please use native `Map` instead [deprecation id: ember-map-deprecation]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17922:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:18024:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17946:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:18024:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:18033:17)\\n        at deprecate (http://localhost:7357/assets/vendor.js:18005:34)\\n        at MapWithDefault.Map (http://localhost:7357/assets/vendor.js:19126:51)\\n        at new MapWithDefault (http://localhost:7357/assets/vendor.js:19522:75)\\n        at Function.create (http://localhost:7357/assets/vendor.js:19542:18)\'\n' }
            { type: 'warn',
              text:
               '\'DEPRECATION: Use of @ember/OrderedSet is deprecated. Please use native `Map` instead [deprecation id: ember-map-deprecation]\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:17922:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:18024:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:17946:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:18024:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:18033:17)\\n        at deprecate (http://localhost:7357/assets/vendor.js:18005:34)\\n        at new OrderedSet (http://localhost:7357/assets/vendor.js:19448:51)\\n        at MapWithDefault.Map (http://localhost:7357/assets/vendor.js:19132:22)\\n        at new MapWithDefault (http://localhost:7357/assets/vendor.js:19522:75)\'\n' }
```

Should we upgrade Ember Data, or is there any other way to remove these warnings?

**Comment by pzuraq** [comment]
I think updating Ember Data makes sense, PRs definitely welcome 😄
