### ISSUE TITLE
v0.5.2: projectVersionDoc.included is not iterable

### ISSUE THREAD

**Issue by nightire** [ember-learn/ember-cli-addon-docs#225]
Getting the following error with `ember-cli-addon-docs@0.5.2`:

```
Build Error (SearchIndexCompiler)

projectVersionDoc.included is not iterable
```

<details>
	<summary>Here is the full error log</summary>

```
=================================================================================

ENV Summary:

  TIME: Tue Aug 21 2018 02:21:53 GMT+0800 (China Standard Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/nightire/Code/choice-form/ui-lottie/node_modules/.bin/ember
  - serve
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/nightire/Code/choice-form/ui-lottie/node_modules/.bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/opt/texinfo/bin
  - /usr/local/opt/sqlite/bin
  - /usr/local/opt/openssl/bin
  - /usr/local/opt/libxml2/bin
  - /usr/local/opt/gettext/bin
  - /usr/local/opt/curl/bin
  - /Users/nightire/.cargo/bin
  - /usr/local/opt/gnu-tar/libexec/gnubin
  - /usr/local/Cellar/zplug/2.4.2/bin
  - /usr/local/sbin
  PLATFORM: darwin x64
  FREEMEM: 44756992
  TOTALMEM: 17179869184
  UPTIME: 624114
  LOADAVG: 5.642578125,3.40283203125,2.5234375
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.8.0
  - openssl: 1.1.0h
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.7.288.49-node.19
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: projectVersionDoc.included is not iterable
    at SearchIndexCompiler.buildApiItemDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:87:40)
    at buildApiItemDocuments.next (<anonymous>)
    at SearchIndexCompiler.buildDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:53:21)
    at buildDocuments.next (<anonymous>)
    at lunr.Builder.<anonymous> (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:32:16)
    at lunr (/Users/nightire/Code/choice-form/ui-lottie/node_modules/lunr/lunr.js:53:10)
    at SearchIndexCompiler.build (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:22:17)
    at /Users/nightire/Code/choice-form/ui-lottie/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:538:13)
  - codeFrame: projectVersionDoc.included is not iterable
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SearchIndexCompiler` plugin. 💥
projectVersionDoc.included is not iterable
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SearchIndexCompiler` plugin. 💥
projectVersionDoc.included is not iterable
  - name: Error
  - nodeAnnotation: SearchIndexCompiler
  - nodeName: SearchIndexCompiler
  - originalErrorMessage: projectVersionDoc.included is not iterable
  - stack: TypeError: projectVersionDoc.included is not iterable
    at SearchIndexCompiler.buildApiItemDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:87:40)
    at buildApiItemDocuments.next (<anonymous>)
    at SearchIndexCompiler.buildDocuments (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:53:21)
    at buildDocuments.next (<anonymous>)
    at lunr.Builder.<anonymous> (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:32:16)
    at lunr (/Users/nightire/Code/choice-form/ui-lottie/node_modules/lunr/lunr.js:53:10)
    at SearchIndexCompiler.build (/Users/nightire/Code/choice-form/ui-lottie/node_modules/ember-cli-addon-docs/lib/broccoli/search-indexer.js:22:17)
    at /Users/nightire/Code/choice-form/ui-lottie/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/nightire/Code/choice-form/ui-lottie/node_modules/rsvp/dist/rsvp.js:538:13)

=================================================================================
```
</details>

and a repro: https://github.com/choice-form/ui-lottie

**Comment by xcambar** [comment]
Also appears in `0.5.1`.

We had to go back to `0.5.0` to avoid the error.

**Comment by samselikoff** [comment]
https://github.com/ember-learn/ember-cli-addon-docs/pull/227 closes.

Master currently has some tailwind bugs but will sort those out before the next release!
