### ISSUE TITLE
Clone + ember serve fails

### ISSUE THREAD

**Issue by sinankeskin** [ember-learn/ember-cli-addon-docs#425]
ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'push' of undefined
    at generateYuiDocJsonApi (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\preprocessors\generate-yuidoc-jsonapi.js:75:23)
    at DocsGenerator.build (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\broccoli\generator.js:23:16)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\broccoli-caching-writer\index.js:149:21
    at tryCatch (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

  - code: [undefined]
  - codeFrame: Cannot read property 'push' of undefined
  - errorMessage: Cannot read property 'push' of undefined
        at DocsGenerator
-~- created here: -~-
    at DocsGenerator.Plugin (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:7:31)
    at new CachingWriter (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\broccoli-caching-writer\index.js:18:10)
    at new DocsGenerator (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\broccoli\generator.js:15:5)
    at Class.createDocsGenerator (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\index.js:9:12)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\lib\models\plugin-registry.js:31:54
    at Array.map (<anonymous>:null:null)
    at PluginRegistry.createDocsGenerators (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\lib\models\plugin-registry.js:31:43)
    at Class.postprocessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\index.js:259:43)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\utilities\addon-process-tree.js:6:25
    at Array.reduce (<anonymous>:null:null)
    at addonProcessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\utilities\addon-process-tree.js:4:32)
    at EmberAddon.addonPostprocessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\broccoli\ember-app.js:866:12)
    at EmberAddon.host.addonPostprocessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-auto-import\js\auto-import.js:108:20)
    at EmberAddon.toTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\broccoli\ember-app.js:1825:17)
    at module.exports (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\ember-cli-build.js:50:14)
    at Builder.readBuildFile (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\builder.js:32:10)
    at ServeTask.run (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\tasks\serve.js:49:7)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\command.js:239:24
    at tryCatcher (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:326:21)
    at invokeCallback (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:498:33)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:562:16
    at flush (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2441:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot read property 'push' of undefined
        at DocsGenerator
-~- created here: -~-
    at DocsGenerator.Plugin (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:7:31)
    at new CachingWriter (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\broccoli-caching-writer\index.js:18:10)
    at new DocsGenerator (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\broccoli\generator.js:15:5)
    at Class.createDocsGenerator (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\index.js:9:12)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\lib\models\plugin-registry.js:31:54
    at Array.map (<anonymous>:null:null)
    at PluginRegistry.createDocsGenerators (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\lib\models\plugin-registry.js:31:43)
    at Class.postprocessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\index.js:259:43)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\utilities\addon-process-tree.js:6:25
    at Array.reduce (<anonymous>:null:null)
    at addonProcessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\utilities\addon-process-tree.js:4:32)
    at EmberAddon.addonPostprocessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\broccoli\ember-app.js:866:12)
    at EmberAddon.host.addonPostprocessTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-auto-import\js\auto-import.js:108:20)
    at EmberAddon.toTree (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\broccoli\ember-app.js:1825:17)
    at module.exports (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\ember-cli-build.js:50:14)
    at Builder.readBuildFile (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\builder.js:52:14)
    at Builder.setupBroccoliBuilder (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\builder.js:66:22)
    at new Builder (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\builder.js:32:10)
    at ServeTask.run (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\tasks\serve.js:49:7)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\lib\models\command.js:239:24
    at tryCatcher (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:326:21)
    at invokeCallback (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:498:33)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:562:16
    at flush (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2441:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: DocsGenerator
  - originalErrorMessage: Cannot read property 'push' of undefined
  - stack: TypeError: Cannot read property 'push' of undefined
    at generateYuiDocJsonApi (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\preprocessors\generate-yuidoc-jsonapi.js:75:23)
    at DocsGenerator.build (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\broccoli\generator.js:23:16)
    at C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\broccoli-caching-writer\index.js:149:21
    at tryCatch (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\Khons\Sites\Javascript\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Windows 10 Pro 1903
node v12.13.0
npm 6.13.0
ember-cli 3.13.1
watchman 4.9.4

I can confirm that this is a **Windows** issue. On WSL (Ubuntu) there is no issue at all.

Thank you.

**Comment by ro0gr** [comment]
looks the same as https://github.com/ember-learn/ember-cli-addon-docs-yuidoc/issues/4

**Comment by sinankeskin** [comment]
Yeap looks like same issue. Sorry.

**Comment by rwwagner90** [comment]
Is anyone using Windows can help us with a fix, that would be great!

**Comment by sinankeskin** [comment]
I've tested. This [PR](https://github.com/ember-learn/ember-cli-addon-docs-yuidoc/pull/9) fixing this issue but latest version (v0.2.1) doesn't have that fix.

I guess release a new npm package (ember-cli-addon-docs-yuidoc) version would be suffice.

Thank you.

**Comment by rwwagner90** [comment]
@pzuraq do you have permissions to release? If you want to add me to these packages on npm, I can release as well.

**Comment by pzuraq** [comment]
I'll add you to it

**Comment by rwwagner90** [comment]
@sinankeskin released 0.2.3!

**Comment by sinankeskin** [comment]
Thank you. Appreciate it.
