### ISSUE TITLE
Deprecation warning for serializer with newer Ember Data versions

### ISSUE THREAD

**Issue by bitwolfe** [ember-learn/ember-cli-addon-docs#439]
Getting the following deprecation warning when running AddonDocs on Ember 3.15 with matching Ember Data version, but probably affects a few earlier versions too.

```
WARN: DEPRECATION: store.serializerFor("project") resolved the "-addon-docs" serializer via the deprecated `adapter.defaultSerializer` property.

Previously, if no application or type-specific serializer was specified, the store would attempt to lookup a serializer via the `defaultSerializer` property on the type's adapter. This behavior is deprecated in favor of explicitly defining a type-specific serializer or application serializer [deprecation id: ember-data:default-serializer] See https://deprecations.emberjs.com/ember-data/v3.x#toc_ember-data:default-serializers for more details.
                    at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:49179:21)
                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:49276:9)
                    at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:49206:9)
                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:49276:9)
                    at invoke (http://localhost:7357/assets/vendor.js:49288:9)
                    at Object.deprecate (http://localhost:7357/assets/vendor.js:49244:28)
                    at DefaultStore.serializerFor (http://localhost:7357/assets/vendor.js:119491:37)
                    at http://localhost:7357/assets/vendor.js:115918:30
                    at invokeCallback (http://localhost:7357/assets/vendor.js:73387:17)
```

**Comment by rwwagner90** [comment]
Sounds like we need to define a serializer. Would you be interested in opening a PR for this @bitwolfe?
