### ISSUE TITLE
Does this support apps as well?

### ISSUE THREAD

**Issue by bravo-kernel** [ember-learn/ember-cli-addon-docs#75]
Probably a very silly question but would we be able to use this addon for documenting our main project/app as well (or is it only intended/suitable for Ember addons)?

**Comment by pzuraq** [comment]
No question is silly 😄

Currently this addon only supports addons, and we’re focusing on making the DX for them as smooth as possible. In the future I think the core components and generators could be extracted to work with both, would definitely like to see it happen!

**Comment by bravo-kernel** [comment]
Thanks for confirming and good luck with this project, it looks amazing !

**Comment by leggomuhgreggo** [comment]
Hey! Had the same question -- was wondering if there'd been any action. Should this be represented as a [`Feature / Enhancement`](https://github.com/ember-learn/ember-cli-addon-docs/issues?q=is%3Aissue+label%3A%22Feature+%2F+Enhancement%22+is%3Aopen) issue? Thanks!

**Comment by pzuraq** [comment]
Yup, I think this would be a good roadmap item or feature request. I don't think we can commit to shipping it any time soon, but it should be up there to remind us and so folks know where we are on it.

**Comment by dfreeman** [comment]
Agreed—I don't think this question is going to stop coming up 🙂

**Comment by ilovethebends** [comment]
Is this the same for in-repo addons?

**Comment by mike-engel** [comment]
Unfortunately this still doesn't work for documenting apps, at least following the guide @rwwagner90 linked to. Ember returns this error when running `ember serve`:

```
cio at /Users/mike/projects/ui is missing its addon main file
```

This is the stack trace from the debug log:
```
stack: Error: cio at /Users/mike/projects/ui is missing its addon main file
    at PackageInfo.getAddonConstructor (/Users/mike/projects/ui/docs/node_modules/ember-cli/lib/models/package-info-cache/package-info.js:386:13)
    at /Users/mike/projects/ui/docs/node_modules/ember-cli/lib/models/instantiate-addons.js:73:38
    at Vertices.each (/Users/mike/projects/ui/docs/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/Users/mike/projects/ui/docs/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/Users/mike/projects/ui/docs/node_modules/dag-map/dag-map.umd.js:68:24)
    at instantiateAddons (/Users/mike/projects/ui/docs/node_modules/ember-cli/lib/models/instantiate-addons.js:54:9)
    at Project.initializeAddons (/Users/mike/projects/ui/docs/node_modules/ember-cli/lib/models/project.js:457:19)
    at Project.eachAddonCommand (/Users/mike/projects/ui/docs/node_modules/ember-cli/lib/models/project.js:518:12)
    at module.exports (/Users/mike/projects/ui/docs/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.maybeMakeCommand (/Users/mike/projects/ui/docs/node_modules/ember-cli/lib/cli/cli.js:94:26)
```

Unfortunately I don't know too much about ember internals, but it seems like `ember-cli-addon-docs` requires that the parent project being documented is an addon, even if it's being used as a standalone app.
