### ISSUE TITLE
Cannot read property 'program' of undefined

### ISSUE THREAD

**Issue by csprocket777** [ember-learn/ember-cli-addon-docs#915]
I've setup `ember-cli-addon-docs` in my addon but when I go to serve it up to develop the docs I get a build error:

`Cannot read property 'program' of undefined`

#### Broccoli Plugin: DocsGenerator
```
Cannot read property 'program' of undefined
        at DocsGenerator
-~- created here: -~-
    at DocsGenerator.Plugin (/Users/[...addon directory path...]/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/Users/[...addon directory path...]/node_modules/broccoli-caching-writer/index.js:18:10)
    at new DocsGenerator (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/lib/broccoli/generator.js:16:5)
    at Class.createDocsGenerator (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/index.js:11:12)
    at /Users/[...addon directory path...]/node_modules/ember-cli-addon-docs/lib/models/plugin-registry.js:32:11
    at Array.map (<anonymous>)
    at PluginRegistry.createDocsGenerators (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs/lib/models/plugin-registry.js:31:43)
    at Class.postprocessTree (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs/index.js:315:43)
    at /Users/[...addon directory path...]/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
-~- (end) -~-
```

And then what looks to be 3 expressions of the same error below that:
```
TypeError: Cannot read property 'program' of undefined
    at DocFactory._inspectExportDefaultDeclaration (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/Factory/DocFactory.js:136:40)
    at new DocFactory (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/Factory/DocFactory.js:91:10)
    at Function._traverse (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:232:21)
    at /Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:114:25
    at Function._walk (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:203:9)
    at Function._walk (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:205:14)
    at Function._walk (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:205:14)
    at Function._walk (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:205:14)
    at Function._walk (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:205:14)
    at Function.generate (/Users/[...addon directory path...]/node_modules/ember-cli-addon-docs-esdoc/node_modules/esdoc/out/src/ESDoc.js:98:10)
              
```

```
❯ ember version --verbose && npm --version && yarn --version
ember-cli: 3.24.0
node: 14.17.3
v8: 8.4.371.23-node.67
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
os: darwin x64
6.14.13
1.22.10
```

**Comment by rwwagner90** [comment]
@csprocket777 can you please try the master branch? I've been working on modernizing everything.

**Comment by rwwagner90** [comment]
@csprocket777 please try the latest, 4.0.2 and let me know if you are still experiencing issues!

**Comment by csprocket777** [comment]
I am not experiencing the same issue after using 4.0.2. i'm experiencing a different issue now. Shall I open a different ticket?

**Comment by rwwagner90** [comment]
@csprocket777 yes please, I will close this one.
